from __future__ import annotations
import json
from pathlib import Path

from fastapi import APIRouter, Depends, Request, status

from . import admin as shared
from .deps import get_container
from backend.md_quiz.config import BASE_DIR
from backend.md_quiz.storage.db import (
    _check_admin_password,
    _hash_admin_password,
    get_admin_user_by_username,
    update_admin_user_password,
)

router = APIRouter()


def _get_build_version() -> dict:
    """Read the version.json generated by scripts/gen-version.sh."""
    version_path = BASE_DIR / "static" / "version.json"
    if version_path.exists():
        try:
            return json.loads(version_path.read_text(encoding="utf-8"))
        except Exception:
            pass
    # Fallback when version.json hasn't been generated
    from datetime import UTC, datetime
    return {"version": "V00.00.00.000-[dev]-(0000000)", "base": "00.00.00", "build": 0, "branch": "dev", "commit": "0000000"}


@router.get("/version")
def get_version():
    return _get_build_version()


@router.post("/session/login")
def login(payload: shared.AdminLoginPayload, request: Request):
    user = get_admin_user_by_username(payload.username)
    if not user or not _check_admin_password(payload.password, user["password_hash"]):
        raise shared.HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="账号或密码错误")
    request.session["admin_logged_in"] = True
    request.session["admin_username"] = payload.username
    request.session["admin_role"] = user["role"]
    return {"ok": True, "username": payload.username, "role": user["role"]}


@router.post("/session/logout")
def logout(request: Request):
    request.session.clear()
    return {"ok": True}


@router.get("/session")
def session(request: Request):
    return {
        "authenticated": bool(request.session.get("admin_logged_in")),
        "username": request.session.get("admin_username"),
        "role": request.session.get("admin_role"),
    }


@router.put("/session/password")
def change_own_password(payload: shared.AdminUserChangeOwnPasswordPayload, request: Request):
    """当前登录管理员自助修改自己的密码（任何角色可用，仅能改自己）。"""
    shared._require_admin(request)
    username = str(request.session.get("admin_username") or "").strip()
    if not username:
        raise shared.HTTPException(status_code=401, detail="未登录")
    user = get_admin_user_by_username(username)
    if not user:
        raise shared.HTTPException(status_code=404, detail="账户不存在")
    if not _check_admin_password(payload.old_password, user["password_hash"]):
        raise shared.HTTPException(status_code=400, detail="原密码不正确")
    new_hash = _hash_admin_password(payload.new_password)
    update_admin_user_password(int(user["id"]), new_hash)
    return {"ok": True}


@router.get("/bootstrap")
def bootstrap(request: Request, container=Depends(get_container)):
    shared._require_admin(request)
    role = str(request.session.get("admin_role") or "").strip()
    is_super = role == "super_admin"
    runtime_config = container.runtime_service.get_runtime_config().model_dump()
    nav = [
        {"key": "assignments", "label": "邀约与答题", "href": "/admin/assignments"},
        {"key": "quizzes", "label": "测验", "href": "/admin/quizzes"},
        {"key": "quiz-analytics", "label": "测验分析", "href": "/admin/quiz-analytics"},
        {"key": "job-descriptions", "label": "职位管理", "href": "/admin/job-descriptions"},
        {"key": "candidates", "label": "候选人", "href": "/admin/candidates"},
    ]
    if is_super:
        nav.append({"key": "accounts", "label": "账户管理", "href": "/admin/accounts"})
        nav.append({"key": "logs", "label": "系统日志", "href": "/admin/logs"})
        nav.append({"key": "status", "label": "系统状态", "href": "/admin/status"})
    return {
        "role": role,
        "brand": {"name": "MD Quiz", "theme": runtime_config.get("ui_theme_name") or "blue-green"},
        "navigation": nav,
        "runtime_config": runtime_config if is_super else {},
        "cards": [
            {"label": "后端架构", "value": "FastAPI + Worker + Scheduler"},
            {"label": "后台入口", "value": "/admin"},
            {"label": "兼容跳转", "value": "/legacy/* -> /*"},
        ],
    }


@router.get("/config")
def get_runtime_config(request: Request, container=Depends(get_container)):
    shared._require_admin(request)
    return container.runtime_service.get_runtime_config().model_dump()


@router.put("/config")
def update_runtime_config(payload: shared.RuntimeConfigPatch, request: Request, container=Depends(get_container)):
    shared._require_admin(request)
    updates = payload.model_dump(exclude_none=True)
    return container.runtime_service.update_runtime_config(updates).model_dump()


@router.get("/jobs")
def list_jobs(request: Request, container=Depends(get_container)):
    shared._require_admin(request)
    return {"items": [item.model_dump() for item in container.job_service.list_jobs()]}


@router.get("/jobs/{job_id}")
def get_job(job_id: str, request: Request, container=Depends(get_container)):
    shared._require_admin(request)
    job = container.job_service.get_job(job_id)
    if job is None:
        raise shared.HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="任务不存在")
    return job.model_dump()


@router.post("/jobs", status_code=status.HTTP_201_CREATED)
def enqueue_job(payload: shared.EnqueueJobPayload, request: Request, container=Depends(get_container)):
    shared._require_admin(request)
    job = container.job_service.enqueue(payload.kind, payload=payload.payload, source="admin-api")
    return job.model_dump()
